kernelci/kernelci-deploy

patches/kernelci-core/0001-STAGING-bisect.jpl-add-staging-in-tags-and-email-sub.patch
patches/kernelci-core/0002-STAGING-build-configs.yaml-add-kernelci_staging-buil.patch
patches/kernelci-core/0003-STAGING-build-configs.yaml-build-arm64-BIG_ENDIAN-wi.patch
patches/kernelci-core/0004-STAGING-test-configs.yaml-enable-boot-and-baseline-w.patch
patches/kernelci-core/0005-STAGING-ensure-no-public-bisection-email-reports-are.patch
patches/kernelci-core/0006-STAGING-only-send-emails-for-kernelci-tree.patch
patches/kernelci-core/0007-STAGING-build-configs-add-kselftest-fragment-to-stab.patch

Before:
```
$ ./kci_build list_kernel_configs --arch arm64 --kdir $HOME/work/kernel/linux --config kernelci
arm64 defconfig gcc-8
arm64 tinyconfig gcc-8
arm64 allnoconfig gcc-8
```
After:
```
$ ./kci_build list_kernel_configs --arch arm64 --kdir $HOME/work/kernel/linux --config kernelci
arm64 defconfig gcc-8
arm64 defconfig+kernel/configs/kselftest.config gcc-8
arm64 allnoconfig gcc-8
arm64 tinyconfig gcc-8
```

patches: add patch for kselftest fragment

---

patches/linux/staging-next/0001-selftests-futex-Add-futex-wait-test.patch
patches/linux/staging-next/0002-selftests-futex-Add-futex-compare-requeue-test.patch
patches/linux/staging-next/0003-unicode-Implement-UTF-8-tests-as-a-KUnit-test.patch

Update kselftest's futex patches to the more updated one sent to the mailing list.

patches/linux/staging-next: Update futex patches

---

patches/kernelci-backend/chromeos.kernelci.org/0001-CHROMEOS-Update-configuration-for-chromeos.kernelci..patch
patches/kernelci-backend/chromeos.kernelci.org/0002-CHROMEOS-Change-BASE_PATH-for-storage.chromeos.kerne.patch
patches/kernelci-backend/chromeos.kernelci.org/0003-CHROMEOS-Update-config-file-paths.patch
patches/kernelci-core/chromeos.kernelci.org/0001-CHROMEOS-build-configs.yaml-add-kernelci_chromeos-bu.patch
patches/kernelci-core/chromeos.kernelci.org/0002-CHROMEOS-ensure-no-public-bisection-email-reports-ar.patch
patches/kernelci-core/chromeos.kernelci.org/0003-CHROMEOS-use-chromeos.kernelci.org-branch-for-test-d.patch
patches/kernelci-core/chromeos.kernelci.org/0004-CHROMEOS-use-kernelci-staging-qemu-Docker-image.patch
patches/kernelci-frontend/chromeos.kernelci.org/0001-CHROMEOS-Set-defaults-for-chromeos.kernelci.org.patch
patches/kernelci-jenkins/chromeos.kernelci.org/0001-CHROMEOS-bisect.jpl-add-chromeos-in-tags-and-email.patch
patches/kernelci-jenkins/chromeos.kernelci.org/0002-CHROMEOS-only-send-emails-for-kernelci-tree.patch

Add sets of patches needed for the chromeos.kernelci.org instance in separate directories.

Add patches for chromeos.kernelci.org

---

data/chromeos.ini

As Jeny work on ChromeOS project tasks and some of PR need testing on staging, we need to add username on trusted list.

chromeos.ini: Add JenySadadia to chromeos trusted list

---

data/staging.ini

Add user to allow his PR to be tested on staging

staging.ini: Add nkbelin from BayLibre

---

data/chromeos.ini

Laura is already trusted for staging and as some of PR touch chromeos branch, we need to add this user to chromeos.ini as well.

chromeos.ini: Add laura-nao as trusted user

---

scheduler/install-scheduler.sh

After testing i found few minor bugs
* stop old services, so they can be updated properly on reload
* Add more verbosity for easier troubleshooting
* Remove extra suffix for services and timers

scheduler: Add few fixes

---

data/chromeos.ini
data/staging.ini

Arnaud Ferraris (a-wai) started contributing to project, and we need his patches to be tested on staging and i expect him to contribute on both main branch and chromeos.

chromeos/staging.ini: Add Arnaud Ferraris

---

patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch

According to PR https://github.com/kernelci/kernelci-core/pull/2039/commits/76e133a2b8aa23d4c8312c65d76abbe740be1317 we need to update rust version on staging too.

0001-STAGING-add-build-configs-staging.yaml.patch: Update rust version

---

data/chromeos-monitor.json

As @a-wai added new kernel, we need to add it to monitor list as well.

Add 6.6 kernel

---

kubernetes/README.md
kubernetes/api-pipeline-deploy.sh
kubernetes/config/pipeline.yaml
kubernetes/deploy.cfg.example
kubernetes/manifests/issuer.yaml

Add initial deploy files for kernelci-api and kernelci-pipeline. Also add manifest for cert-manager, which is common for both.
Depends-on: https://github.com/kernelci/kernelci-pipeline/pull/354
Depends-on: https://github.com/kernelci/kernelci-api/pull/393

kubernetes: Add API/Pipeline deploy script

---

patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch
patches/kernelci-core/staging.kernelci.org/0002-STAGING-ensure-no-public-bisection-email-reports-are.patch
patches/kernelci-core/staging.kernelci.org/0003-STAGING-use-kernelci-staging-qemu-Docker-image.patch
patches/kernelci-core/staging.kernelci.org/0004-STAGING-use-staging.kernelci.org-branch-for-test-def.patch
patches/kernelci-core/staging.kernelci.org/0005-STAGING-use-staging-branch-for-buildroot-with-reduce.patch
patches/kernelci-core/staging.kernelci.org/0006-STAGING-use-staging-JWT-in-kubernetes-template.patch
staging.kernelci.org

(Following the instructions at https://github.com/kernelci/kernelci-core/pull/2124#issuecomment-1752543868)
Could a sysadmin please create the `kernelci/staging-rustc-1.74` and `kernelci/rustc-1.74` repositories on Docker hub?
See also: https://github.com/kernelci/kernelci-core/pull/2250 and https://github.com/kernelci/kernelci-deploy/pull/114.

Rust 1.74 (staging)

---

staging.kernelci.org

Change pidfile path and set variable, to avoid permission issues

staging.kernelci.org: Change pidfile path

---

tools/kci-rootfs.py

For building staging images recommended also to use staging- debos and so.

kci-rootfs: Add staging flag

---

staging.kernelci.org

staging.kernelci.org: Make current tag as latest

---

kubernetes/create_kci_k8s_azure_build.sh

Cluster created with spot instances, cost limits, to stay within planned monthly budget and same time benefit from reduced costs of Spot instances.

k8s: Add script creating Azure K8S computing cluster

---

patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch
patches/kernelci-core/staging.kernelci.org/0002-STAGING-ensure-no-public-bisection-email-reports-are.patch
patches/kernelci-core/staging.kernelci.org/0003-STAGING-use-kernelci-staging-qemu-Docker-image.patch
patches/kernelci-core/staging.kernelci.org/0004-STAGING-use-staging.kernelci.org-branch-for-test-def.patch
patches/kernelci-core/staging.kernelci.org/0005-STAGING-use-staging-branch-for-buildroot-with-reduce.patch
patches/kernelci-core/staging.kernelci.org/0006-STAGING-use-staging-JWT-in-kubernetes-template.patch

Add -rt patches

---

data/staging.ini

Helen Fornazier (helen-fornazier) joining the project to contribute on several topics related to KCIv2.

contributors: Add Helen as contributor

---

staging.kernelci.org

Add lava-callback for production deployment

staging.kernelci.org: Add lava-callback recipe

---

tools/azure_files_cleanup.py
tools/docker_images_cleanup.py

We need to do housekeeping to not exceed reasonable limits in storage we are consuming.
Adding few tools i developed.

Add few more tools

---

kubernetes/api-pipeline-deploy.sh
kubernetes/api-production-update.sh
kubernetes/create_kci_k8s_azure_build.sh
localinstall/.env-api
localinstall/1-rebuild_all.sh
localinstall/2-install_api.sh

1)Add script for API/Pipeline production update
api-production-update.sh
2)pipeline deploy more complete script, as several fragments are added, and new images created, such as lava-callback 3)Various late fixes for kci-easy/localinstall

Various updates

---

kubernetes/api-pipeline-deploy.sh
kubernetes/create_kci_k8s_azure_build.sh

1)Patch nginx to accept larger body size (LAVA callback) 2)Update mongo-backup/restore scripts
3)Add mongo-shell kubectl exec shortcut

kubernetes: Various updates

---

kubernetes/api-pipeline-deploy.sh
tools/azure_files_cleanup.py
tools/docker_images_cleanup.py

k8s update - kubectl cp for directory didn't worked well, use tgz 
azure cleanup - use sqlite for caching and async threadpool for speedup 
docker cleanup - remove images/tags created long time ago

Updates: k8s, azure cleanup, docker cleanup

---

data/staging.ini

Add mwasilew to the list of trusted GitHub users.

data/staging.ini: add mwasilew to the list of users

---

patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch

Yes i know i need to regenerate patches, but i need to keep legacy working just 1-2 month more.

patches: Quick hack to update gcc-10 to gcc-12

---

kubernetes/api-pipeline-deploy.sh
kubernetes/api-production-update.sh
tools/docker_images_cleanup.py

As we reached maturity of this subsystem, we need to deploy production instance.

kubernetes: Add deploy of KCIDB bridge

---

data/staging.ini

Add @denisyuji as trusted, so staging can verify his PR

Add denisyuji as trusted user to staging

---

tools/kci-dockerwatch.py

This tool will watch specific pattern of containers and store their logs to storage.
Also it will alert over bot if any of containers are crashing, detecting exception by keyword.

feat(kci-dockerwatch): Add persistent staging logging tool

---

tools/kci-pending.py

When we create staging environment, we need to apply all pending PR patches, if user are added in "allowlist" as trusted.

feat(kci-pending): Add tool to create staging snapshots

---

tools/kci-pending.py

We need PAT token to push over workflows, adding support.

feat(kci-pending): Add support of push with PAT token

---

kubernetes/api-pipeline-deploy.sh
kubernetes/api-production-update.sh

Automate update of configuration files

feat(k8s): Update configuration files during production update

---

kubernetes/api-pipeline-deploy.sh
kubernetes/api-production-update.sh

Regression job was missing in production update scripts

fix(k8s): Add regression to deploy scripts

---

tools/kci-dockerwatch.py

On repeating error bot might become too noisy, add throttling.

feat(kci-dockerwatch): Add message throttling

---

kubernetes/api-pipeline-deploy.sh
kubernetes/api-production-update.sh
tools/kci-dockerwatch.py

kci-dockerwatch disable messaging by default
add new commands for deploy (e.g. update secrets only, if sas token need update) production update require pods restart to make sure new config is taken

fixes: production updates, new commands for deploy, kci-dockerwatch

---

tools/kci-k8swatch.py

We need similar to dockerwatch tool, but for k8s, to spot errors in k8s pods. Adding initial version of it.

feat(kci-k8swatch.py): Add basic tool to monitor k8s pods logs

---

staging.kernelci.org

We need to start removing legacy procedures, before we convert this script to github actions.

upd(staging.kernelci.org): Gradually remove legacy stuff

---

localinstall/2-install_api.sh
localinstall/4-start-cycle.sh

New docker-compose is included in docker, and called as "docker compose".

fix: Support new "docker compose" command

---

data/staging.ini

@benjamingaignard is developing new rootfs which need to be tested on staging system.

upd(staging.ini): Add benjamingaignard to trusted users

---

kubernetes/README.md

We rewrite documentation, as deployment and components significantly changed.

fix(kubernetes/README.md): Update documentation for new setup

---

kubernetes/api-production-update.sh
playbooks/production/main.yml
playbooks/production/roles/common/tasks/main.yml
playbooks/production/roles/storage/tasks/main.yml
playbooks/production/roles/storage/templates/kernelci-storage.service.j2
playbooks/production/roles/storage/templates/kernelci-storage.toml.j2

1)Update playbooks to install storage from Docker
2)Update deploy script with workflows option, to not build docker images from github workflows, as there is separate process for that.

upd(api-production-update.sh/playbooks): Misc updates

---

tools/firmware-updater.py

This is temporary workaround to solve linux-firmware fetching issues.
This script must run on storage, to keep updating linux-firmware

add(firmware-updater): Add periodic firmware updater for storage

---

kubernetes/api-pipeline-deploy.sh

id_rsa secret is required for NIPA update service

upd(api-pipeline-deploy.sh): Add id_rsa secret

---

playbooks/production/main.yml
playbooks/production/roles/common/tasks/main.yml
playbooks/production/roles/kernelci/handlers/main.yml
playbooks/production/roles/kernelci/tasks/main.yml
playbooks/production/roles/kernelci/vars/main.yml
playbooks/production/roles/webserver/tasks/main.yml

And add missing firmware-updater tool

(ansible) Update ansible recipes

---

playbooks/production/roles/kernelci/tasks/main.yml

Based on real deploy experience update recipes

(ansible): Update ansible again

---

kubernetes/api-pipeline-deploy.sh
kubernetes/extract_secret.py

Sometimes we update toml, for example lab tokens and etc, we need to have easy tooling for that, so this task wont take too much time.

Add tooling to update toml file in kubernetes

---

playbooks/production/main.yml
playbooks/production/roles/storage/tasks/main.yml
playbooks/production/roles/storage/templates/storage-docker-compose.yaml.j2
playbooks/production/roles/webserver/templates/vhost.j2
playbooks/production/roles/webserver/vars/main.yml

Add ansible recipes and fixes to deploy also storage solution written in Rust

Add more IaC for storage

---

staging.kernelci.org

Cleanup unused items and add workaround when docker get stuck due orphaned (not really) network.

Cleanup and workaround docker bug

---

tools/kci-pending.py

We keep hitting rate limits, add token support to bypass github limits.

Add token support

---

tools/kci-pending.py

Trying to apply all known workarounds.
We are not alone,
https://github.com/orgs/community/discussions/157887

Mitigate new ratelimit issue

---

kubernetes/api-pipeline-deploy.sh

1)Mongo restore need rewriting, as we use archive now
2)Require id_rsa key before full deploy
3)globs not supported in config directory specification, remove glob from default value

Minor fixes
