kernelci/kernelci-deploy

patches/linux/staging-next/0001-selftests-futex-Create-futex-wait-tests.patch
patches/linux/staging-next/0002-unicode-Implement-UTF-8-tests-as-a-KUnit-test.patch

Add work-in-progress patch from Ricardo to enable UTF-8 Kunit.

patches/linux/staging-next: add KUnit patch from Ricardo

---

pending.py

Rather than always checking out the 'main' branch, use the --main
command line argument to check out the base branch before merging PRs
and applying patches.

pending.py: use the --main arg when checking out the base branch

---

ansible
kernelci.org

Add an argument to the ansible helper script to specify the revision
of the playbook to use from the config git repository.  Update
kernelci.org accordingly to use the 'main' branch.

ansible: add argument with Ansible playbook git revision

---

chromeos.kernelci.org
data/chromeos-monitor.json
data/chromeos.ini

Add the chromeos.kernelci.org script to automatically deploy and run
jobs for the chromeos.kernelci.org instance.  Also include config
files needed to update the test branches and run Jenkins jobs.

chromeos.kernelci.org: add script with config files

---

patches/buildroot/0001-STAGING-skip-hash-for-bootrr.patch

Use the staging.kernelci.org branch when building bootrr and skip the
hash for staging since it's a moving target.

patches/buildroot: use staging branch for bootrr

---

kernelci.org

Replace current sed based implementation with kci_rootfs update_rootfs_urls which improves update process and enables updates of only these rootfs URLs which are present in the given version.
Signed-off-by: Michal Galka <michal.galka@collabora.com>

kernelci.org: Use kci_test update_rootfs_urls to update rootfs versions

---

chromeos.kernelci.org
patches/kernelci-jenkins/staging.kernelci.org/0004-STAGING-jobs.groovy-add-chromeos-jobs.patch

As ChromeOS uses different set of docker images, we need to build them in deploy script.

chromeos.kernelci.org: Add building new docker images for ChromeOS

---

patches/kernelci-jenkins/staging.kernelci.org/0004-STAGING-jobs.groovy-add-chromeos-jobs.patch

As in PR #21 we change prefix for ChromeOS images, i forgot to update one of Jenkins tasks prefix.

Add one more missing patch for ChromeOS docker prefix

---

staging.kernelci.org

At current moment we decided to keep rootfs built old way, with git clone (without using fragment).
Additionally debos have conflicts on pyyaml versions with kernelci-core tools, so fragment need to be removed for now to fix staging.

staging.kernelci.org: Remove kernelci fragment

---

patches/kernelci-pipeline/staging.kernelci.org/0001-STAGING-config-staging.kernelci.org.conf-add-file-fo.patch

Need to add the section name for `regression_tracker` script in the staging configuration.
Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>

T35922 patches/kernelci-pipeline: add `regression_tracker` section

---

patches/kernelci-pipeline/staging.kernelci.org/0001-STAGING-config-staging.kernelci.org.conf-add-file-fo.patch

Since some services are dropped from the pipeline like `complete_hack` and `set_complete`, need to drop the sections for the scripts from the staging configuration file.
Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>

T38452 patches/kernelci-pipeline: drop config sections of removed scripts

---

data/staging.ini

Add Aishwarya TCV (who's working on KernelCI inside Arm) to the list of trusted users.
Signed-off-by: Mark Brown <broonie@kernel.org>

data/staging.ini: Add Aishwarya TCV to the list of trusted users

---

staging.kernelci.org

As in production, we need to have no-cache argument to have Docker containers content properly updated.

staging.kernelci.org: Add --no-cache argument

---

data/staging.ini

Add Vince Hillier who is a KernelCI project sysadmin to trusted users.
Signed-off-by: Michal Galka <michal.galka@collabora.com>

data/staging.ini: Add Vince Hillier to the list of trusted users

---

patches/kernelci-pipeline/staging.kernelci.org/0001-STAGING-config-staging.kernelci.org.conf-add-file-fo.patch

Set 'kernelci-api' as origin to indentify submitter system.
Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>

T39195 patches/kernelci-pipeline: add `origin` to `send_kcidb` section

---

kernelci.org
staging.kernelci.org

Rust toolchain docker image recipe has been added recently. This commit adds this image to be build during production and staging updates.

kernelci.org/staging.kernelci.org: Add building rustc docker image

---

patches/kernelci-pipeline/staging.kernelci.org/0001-STAGING-config-staging.kernelci.org.conf-add-file-fo.patch

Update origin to be 'kernelci_api' to fix invalid
schema error for `kernelci-api` value.
Signed-off-by: Jeny Sadadia <jeny.sadadia@collabora.com>

T39195 patches/kernelci-pipeline: update `origin` to `kernelci_api`

---

patches/kernelci-jenkins/chromeos.kernelci.org/0001-CHROMEOS-bisect.jpl-add-chromeos-in-tags-and-email.patch

One of patches are outdated and blocking staging ChromeOS runs.
```
Applying patch: patches/kernelci-jenkins/chromeos.kernelci.org/0001-CHROMEOS-bisect.jpl-add-chromeos-in-tags-and-email.patch
error: patch failed: jobs/bisect.jpl:515
error: jobs/bisect.jpl: patch does not apply
```
This should fix issue

bisect.jpl...patch: Fix outdated patch

---

kernelci.org

During weekly production updates only debos and buildroot rootfs images are built.
Add ROOTFS_TYPE parameter to make sure that others are not build when kernelci.org rootfs command is called.

kernelci.org: Limit rootfs builds to buildroot and debos types

---

staging.kernelci.org

update.py by default fetch main branch, while for iec-security and test-definitions we use kernelci.org branch for rebasing. As result these 2 repositories was not tested on staging. Add argument --main that will specify "source" branch to merge pending PR with it.

staging.kernelci.org: Fix "source" branch name

---

kernelci.org
staging.kernelci.org

Add building rustc-1.66 image to cmd_docker in kernelci.org and staging.kernelci.org
Depends on: https://github.com/kernelci/kernelci-core/pull/1597

kernelci.org/staging.kernelci.org: Build rustc-1.66 docker images

---

kernelci.org

kci_test update_rootfs_urls was returining invalid exit code, hence a workaround was applied to determine command's pass/fail state. As kci_test exit code issue is fixed the workaround can be removed.
Depends on https://github.com/kernelci/kernelci-core/pull/1545

kernelci.org: Remove workaround for kci_test update_rootfs_urls

---

patches/kernelci-core/staging.kernelci.org/0006-STAGING-add-multi_v5_defconfig-with-gcc-10.patch

In order to support work on changes to run kselftest on ARMv5 targets replace our staging v5 coverage of at91_dt_defconfig with multi_v5_defconfig since that should support generation of kselftest jobs in the existing configurations.
Signed-off-by: Mark Brown <broonie@kernel.org>

patches/kernelci-core: Substitute at91_dt_defconfig with multi_v5_defconfig

---

staging.kernelci.org

As part of enabling coverage of kselftest for clang builds archiecture specific Docker containers are being added containing libraries needed to build real userspace applications.  Include these in the set of containers we build for staging, leaving the existing containers in place to avoid disrupting existing usage.
Similar updates will be needed to the production script to deploy this but to minimise the risk of disruption there those will be done separately if this approach progresses.
Signed-off-by: Mark Brown <broonie@kernel.org>

staging.kernelci.org: Build architecure specific clang containers

---

staging.kernelci.org

One danging - left unnoticed and need to be removed. Also in https://github.com/kernelci/kernelci-core/pull/1640 we have riscv64 fragment, not riscv, correct in docker generation arch name.

staging.kernelci.org: Small leftover character fix and arch

---

patches/kernelci-jenkins/staging.kernelci.org/0004-STAGING-jobs.groovy-add-chromeos-jobs.patch

With introduction of storage config, we need to fix storage_url in ChromeOS jobs to storage_config too.

Fix cros storage config in ChromeOS jobs

---

chromeos.kernelci.org

Move the base version for chromeos-stable from 5.15 to 6.1 LTS which is more relevant with the tests we're running now.

chromeos.kernelci.org: use 6.1 LTS for chromeos-stable

---

kernelci.org

Update the `cmd_docker()` function to build the arch-specific Clang images as well as the base ones with just the toolchain.

kernelci.org: build arch-specific clang Docker images

---

chromeos.kernelci.org

As we have on rest of instances, we need to add arch specific container builds.

chromeos.kernelci.org: Add arch specific clang docker builds

---

chromeos.kernelci.org

Previous commit included invalid versions of clang. Update list based on config and k8s queue observation

chromeos.kernelci.org: Update clang list to actually required versions

---

chromeos.kernelci.org

I was confused by k8s list of failed pods, and just figured out that failed clang-13 image with cros fragment is not related to chromeos.kernelci.org instance.

chromeos.kernelci.org: One more update of clang compilers

---

kernelci.org

Based on previous production update, we are missing few builds, such as clang-14 arch specific builds and rustc arch specific x86 builds.

kernelci.org: Add missing builds for production

---

patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch

There's a PR against kernelci-core introducing a new virtual fragment
for kselftest which cuts out the fragments that mainly contribute to
bloating the size and tanking the performance of the image.

build-configs.yaml: Add kselftest-slim to the staging build configs

---

chromeos.kernelci.org

First declaration of of cmd_function looks like a definition that doesn't belong to cheomroes.kernelci.org script. It doesn't break anything, but affects readability. Remove the surplus code.

chormeos.kernelci.org: Remove surplus cmd_kernel function

---

data/chromeos.ini

nfraprado(Nícolas F. R. A. Prado) is already trusted contributor on main branch, but missing in ChromeOS branch.
Adding him on ChromeOS as he have pending patches that need to be tested on staging.

chromeos.ini: Add nfraprado to trusted users in CHROMEOS

---

tools/buildroot_checksum.sh

To improve rootfs generation process, we have to automate step of checksum generation for buildroot packages. This tool takes as argument path to file with package description, generates checksum, and write in appropriate format to .hash file.

buildroot_checksum.sh: Add tool for buildroot checksum calculation

---

data/chromeos-monitor.json

As we added new kernel, collabora-chromeos-kernel, we need to monitor it as well for changes and if any, it will run tests.

chromeos-monitor.json: Add new kernel to monitor job

---

staging.kernelci.org

Jenkins require to use docker images with kernelci fragment, and we are building without, as result jenkins use outdated images.

staging.kernelci.org: Add kernelci fragment to debos and buildroot

---

kernelci.org
staging.kernelci.org

Since the script `kci_docker` to create and build docker images has been converted to `kci docker` command, replace the script with `kci` command in the `kernelci.org` and `staging.kernelci.org` tools.

T41052 Replace `kci_docker` with `kci docker`

---

kernelci.org

Fix below error for `docker` command by adding prefix argument:
"The following arguments or settings are required: --prefix"

T41052 kernelci.org: add `prefix` argument for `docker` command

---

pending.py

Introduce a way to add to staging PRs from branches other than  the one specified in the --main option.
Apart from PRs with a base branch name specified in --main also PRs based on different labels having "staging:<main_branch>" labels will be  merged. <main_branch> is the branch name specified in the --main option.
E.g.
To merge PR based on different barnch to chromeos branch it's enough to  mark it with "staging:chromeos" branch.

pending.py: Include PRs with staging:<main_branch> labels

---

chromeos.kernelci.org

As kci_docker replaced by kci docker, we need to update deploy script.

chromeos.kernelci.org: Update ChromeOS from kci_docker to kci docker

---

chromeos.kernelci.org

kci_docker and kci located in different directories, so update path, which i forgot to do in previous commit.

chromeos.kernelci.org: Change path to kci

---

chromeos.kernelci.org
staging.kernelci.org

In case script failed due some error it should send message to syslog, which can be caught by zabbix. This way we can be aware if staging/chromeos instance deploy scripts or anything else is broken - early.

{chromeos,staging}.kernelci.org: Add trap function for script errors

---

patches/kernelci-jenkins/chromeos.kernelci.org/0002-CHROMEOS-only-send-emails-for-kernelci-tree.patch

First we need to add new tast tests.
Second we need to send more results to staging maillist, and do not process also other emails, to make sure we wont litter anywhere else with ChromeOS instance results. Third we need to add new kernel tree.

0002-CHROMEOS...patch: Update ChromeOS tests, trees, logic

---

staging.kernelci.org

As per https://github.com/kernelci/kernelci-core/pull/1890 we need to start building Rust 1.68.
Update deploy script, first for staging, to test that.

staging.kernelci.org: Start building Rust-1.68

---

data/chromeos-monitor.json

Add the chromeos-stable_6.1-backported-arm64 build to the monitor, so it actually builds and gets tested when the branch is updated.

chromeos-monitor.json: Add chromeos-stable_6.1-backported-arm64

---

patches/kernelci-pipeline/staging.kernelci.org/0001-STAGING-config-staging.kernelci.org.toml-add-file-fo.patch
staging.kernelci.org

Add TOML formatted settings file `staging.kernelci.org.toml` to `kernelci-pipeline`.

patches/kernelci-pipeline: patch for adding TOML settings file

---

scheduler/install-scheduler.sh
scheduler/kci-scheduler-rootfs.service
scheduler/kci-scheduler-rootfs.timer

Instead of making simple timer, i decided to make future-proof script that can be used to schedule simple services related to deploy procedures.
For now it will just schedule rootfs builds at friday morning.
Next step might be this scheduler will track if pull request got merged, and for example if it is monday - run docker images build or something like that.

kci-scheduler: Add scheduler tool to deploy script

---

chromeos.kernelci.org

As ChromeOS actually use "bleeding edge" clang, we need to keep up with clang versions for it.

Update ChromeOS clang to version 17

---

kernelci.org

Rust is updated in kernelci-core to 1.71, time to update it in deploy scripts as well.

kernelci.org: Update rust to 1.71

---

chromeos.kernelci.org

ChromeOS need to be updated to clang-17.

chromeos.kernelci.org: Update to clang-17

---

staging.kernelci.org

As rust updated in main tree, it was forgotted(by me) to make test change done here as permanent. Fixing that.

staging.kernelci.org: Update rust to 1.71

---

patches/kernelci-jenkins/staging.kernelci.org/0001-STAGING-only-send-emails-for-kernelci-tree.patch
patches/kernelci-jenkins/staging.kernelci.org/0002-STAGING-add-docker-compose-volume.patch
patches/kernelci-jenkins/staging.kernelci.org/0003-STAGING-bisect.jpl-add-staging-in-tags-and-email.patch
patches/kernelci-jenkins/staging.kernelci.org/0004-STAGING-jobs.groovy-add-chromeos-jobs.patch

As we disabled bisections, we have to update patch for staging which depends on this part of jobs.groovy.

staging.kernelci.org: Update patches for jobs.groovy

---

patches/kernelci-jenkins/staging.kernelci.org/0001-STAGING-only-send-emails-for-kernelci-tree.patch
patches/kernelci-jenkins/staging.kernelci.org/0002-STAGING-add-docker-compose-volume.patch
patches/kernelci-jenkins/staging.kernelci.org/0003-STAGING-bisect.jpl-add-staging-in-tags-and-email.patch
patches/kernelci-jenkins/staging.kernelci.org/0004-STAGING-jobs.groovy-add-chromeos-jobs.patch

This reverts commit aab52eef98527d51edbb28399e829978542f3149.
As we decided to enable bisections again

Revert "staging.kernelci.org: Update patches for jobs.groovy"

---

patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch

This patch replaces remaining references to x86-chromebook fragments in the staging.kernelci.org configuration patches. It depends on kernelci/kernelci-core#2114.

patches/kernelci-core: rename x86-chromebook to x86-board

---

kernelci.org

Update rust version in production deploy script to 1.73

kernelci.org: update rust to 1.73

---

staging.kernelci.org

As failure might happen at any directory - we need to use absolute path to slack script.

staging.kernelci.org: Add absolute path to slack script

---

patches/linux/linux-6.1.y-arm64-chromeos/0049-media-venus-add-firmware-version-based-check.patch
patches/linux/linux-6.1.y-arm64-chromeos/0050-media-venus-enable-sufficient-sequence-change-suppor.patch

Backport patches from 6.6 to fix VP9 decoding on trogdor Chromebooks.

Backport patches for VP9 decoding on trogdor

---

patches/linux/linux-6.1.y-arm64-chromeos/0019-arm64-dts-mediatek-mt8183-kukui-Couple-VGPU-and-VSRA.patch
patches/linux/linux-6.1.y-arm64-chromeos/0022-arm64-dts-mt8183-pumpkin-Couple-VGPU-and-VSRAM_GPU-r.patch
patches/linux/linux-6.1.y-arm64-chromeos/0023-arm64-dts-mediatek-mt8183-evb-Couple-VGPU-and-VSRAM_.patch

Minor changes in mt8183 dts files caused some of our patches to fail applying starting with 6.1.68. Reflect those changes so we can get 6.1 kernels tested again.

patches: linux-6.1.y-arm64-chromeos: fix for 6.1.68+

---

k8s/aws/build-eksctl.yaml
k8s/aws/build-resources.yaml
k8s/aws/deploy-builder
k8s/aws/teardown-builder
k8s/generic/deploy-builder
k8s/generic/metrics-server.yaml
k8s/generic/teardown-builder
k8s/minikube/deploy-builder
k8s/minikube/teardown-builder

This series adds some scripting for deploying builder clusters, mostly intended as a starting point for building on - at present everything is very crude but since we don't deploy services or otherwise much configure the clusters that's probably fine.
Currently there's no support for either Azure or Google Cloud so it's not actually useful for KernelCI itself yet. Azure's CLI doesn't work for AKS on Debian stable so while I have some scripting I've not really tested it.

k8s builder deployment

---

staging.kernelci.org

In some situations it is possible that staging script might get "stuck" and another run might conflict with it. We add basic pidfile to avoid this.

staging.kernelci.org: Add pidfile to avoid concurrent runs

---

patches/kernelci-core/staging.kernelci.org/0002-STAGING-ensure-no-public-bisection-email-reports-are.patch

Related to https://github.com/kernelci/kernelci-core/pull/2286
The `kci-bisect-push-results` has been converted to the symlink to `kernelci/scripts/kci_bisect_push_results.py` file as part of adding `pyproject.toml` for `kernelci` python packaging. Update the patch for sending bisection email reports for staging accordingly.

patches/kernelci-core: update patch for kci bisection emails

---

staging.kernelci.org

We need newer kernel for arm64 testing on current devices.

Change stable to 6.1 tree

---

tools/kci-rootfs.md
tools/kci-rootfs.py

This tool should replace heavy and fragile Jenkins-way of building rootfs.

kci-rootfs: Add rootfs builder tool

---

kernelci.org
staging.kernelci.org

This PR depends on kernelci/kernelci-core#2332

Build KernelCI API production image

---

staging.kernelci.org

To build correctly api image we need api_reg variable

staging.kernelci.org: Add api_rev to docker flags

---

patches/kernelci-core/staging.kernelci.org/0001-STAGING-add-build-configs-staging.yaml.patch
patches/kernelci-core/staging.kernelci.org/0002-STAGING-ensure-no-public-bisection-email-reports-are.patch
patches/kernelci-core/staging.kernelci.org/0003-STAGING-use-kernelci-staging-qemu-Docker-image.patch
patches/kernelci-core/staging.kernelci.org/0004-STAGING-use-staging.kernelci.org-branch-for-test-def.patch
patches/kernelci-core/staging.kernelci.org/0005-STAGING-use-staging-branch-for-buildroot-with-reduce.patch
patches/kernelci-core/staging.kernelci.org/0006-STAGING-use-staging-JWT-in-kubernetes-template.patch
staging.kernelci.org

Could a sysadmin please create the `kernelci/staging-rustc-1.75` and `kernelci/rustc-1.75` repositories on Docker hub?
Please note that in the staging patches, as usual, I only change the version, but we would like to keep both the latest and the previous latest -- is it needed that we test both here, or just the latest added? Please see my note at https://github.com/kernelci/kernelci-core/pull/2321.
Upgrade PRs:
- https://github.com/kernelci/kernelci-core/pull/2321.
- https://github.com/kernelci/kernelci-deploy/pull/121.
- https://github.com/kernelci/kernelci-deploy/pull/122.

Rust 1.75 (staging)

---

kubernetes/api-pipeline-deploy.sh
tools/legacy_watchdog.py

As we have endless issues with "dashboard is down", we were able to identify 2 reasons:
1)Celery queue getting stuck by some reason
2)OOM
This is workaround of celery queue issues.
This script checks celery queue, and if there is no abnormal load average, it clearly means just celery issue.

legacy_watchdog.py: Add legacy KernelCI watchdog

---

staging.kernelci.org

Add the -F flag when running Hugo to also render pages with a date set in the future.  This is useful for checking changes on staging before they're published in production.
Fixes: #124

staging.kernelci.org: add hugo -F for future pages

---

staging.kernelci.org

In old script api was built in docker recipe, plus rebuilt only if changes in kernelci-api exist, but wont rebuild, if for example we do only changes in kernelci-core.
Now it will rebuild each staging run, as kernelci-core data models might get updated for example.

staging.kernelci.org: Rework api build/restart

---

data/staging.ini

Daniel is a kernel developer working on real time and looking at testing
for the RT stable kernel, allow his PRs to run on staging.
Signed-off-by: Mark Brown <broonie@kernel.org>

data/staging.ini: Allow Daniel Wagner's PRs to run on staging

---

staging.kernelci.org

Rust PR are coming relatively rarely, but rebuilding them on staging takes a lot of time. Let's make it optional, solution is not best how to enable them, but will work for now.

Disable rust builds by default

---

staging.kernelci.org

Last second type caused issues

staging: syntax fixes

---

patches/kernelci-core/staging.kernelci.org/0004-STAGING-use-staging.kernelci.org-branch-for-test-def.patch

Temporary revert as we are doing major migration to bookworm
This reverts commit 31ba2931d0efe163c7594efd902d0222b94226b2.

Revert "kernelci-core/patches: Update rt patch for PR#2397"

---

kernelci.org
staging.kernelci.org

Depends on https://github.com/kernelci/kernelci-core/pull/2495
Due to recent changes in the `api.jinja2` template, `kernelci` docker image has to be built with `api` fragment to run API services. Update `kci docker` command for `api` accordingly in `staging.kernelci.org` and `kernelci.org` scripts.

Use `kernelci` image with `api` fragment

---

staging.kernelci.org

To run k8s with pipeline and docker we need to build pipeline fragment to be built.
Author of commit: Paweł Wieczorek <pawiecz@collabora.com>

staging.kernelci.org: Add pipeline recipe

---

localinstall/.env-api
localinstall/1-rebuild_all.sh
localinstall/2-install_api.sh
localinstall/3-install_pipeline.sh
localinstall/4-start-cycle.sh
localinstall/README.md
localinstall/api-configs.yaml
localinstall/helpers/kci_user_token_admin.exp
localinstall/helpers/scripts_setup_admin_user.exp
localinstall/kernelci-cli.toml
localinstall/main.cfg

This utility has been originally created by:
Denys Fedoryshchenko <denys.f@collabora.com>
Its goal is to provide easy to set up and use environment for the new KernelCI system. It can serve as a local development instance of the system.

Import kci-easy as a new deployment type

---

kernelci.org

Remove unsupported clang options and update to gcc-12.

kernelci.org: Update deploy data to bookworm

---

tools/kci-dockerwatch.py

Triggering by keyword doesn't work well yet, because we have a lot of logging from kcidb-bridge which might contain trigger strings from python crashes on DUT.

fix(kci-dockerwatch): Log crash only if container stops

---

kubernetes/api-pipeline-deploy.sh

k8s credentials required only on pipeline secrets update or full deployment, but not required during ordinary deployment.

fix(api-pipeline-deploy.sh): Do not require k8s credentials always

---

kubernetes/api-production-update.sh

1)Update config without restarting processes. They will (likely) restart later during deployment manifest updates.
2)Add revisions of other components (pipeline, callback) to recipe.

fix(api-production-update.sh): Fix revisions and order of config update

---

tools/kci-pending.py
tools/kci-rootfs.py

1)Fix docker prefix to new scheme (we prefer ghcr.io) 
2)Hard-fail if git failed

fix(kci-pending,kci-rootfs): Fix docker prefix and hard-fail on git errors

---

tools/kci-rootfs.py

Patch 5082d25c5d1d231cac3d25abefe8ad0706da42af changed prefix scheme for Docker images used as rootfs builders. This patch replaces remaining occurences of the old-style prefixed names.

fix(kci-rootfs): Replace remaining misprefixed Docker image names

---

tools/kci-rootfs.py

Patch 5082d25c5d1d231cac3d25abefe8ad0706da42af changed prefix scheme for Docker images used as rootfs builders.
Previously prefixes differentiated only staging and production images ("staging-" vs. empty prefix). Now they may also include container registry information (with fallback to Docker Hub if omitted).
This patch changes default value of the prefix to separate container registry information from Docker image name. By default:
- production images
- taken from ghcr.io registry
will be used.

fix(kci-rootfs): Change default rootfs builder Docker image prefix

---

kubernetes/api-pipeline-deploy.sh

On ordinary k8s deploy and config update we dont need API_TOKEN, MONGO URI and etc.

fix(k8s deploy): Do not require some secrets on config update

---

kubernetes/manifests/issuer.yaml

We have new domain, so we need to update issuer manifest

(k8s) Add api.kernelci.org to issuer.yaml for tls generation

---

tools/kci-pending.py

We had temporary name, but now rolling final new staging system, time to update branch name.

(tools/kci-pending.py) Fix branch name to current staging.kernelci.org

---

staging.kernelci.org

This check faulty, better to remove it

(staging.kernelci.org): Dont verify jq

---

tools/kci-rootfs.py

The --staging argument was removed, but a check for it remained. Remove the obsolete check and update the warning message to reflect the new prefix handling via --prefix.

kci-rootfs: remove obsolete --staging check

---

localinstall/1-rebuild_all.sh
localinstall/3-install_pipeline.sh

This PR fixes the following issue when starting a local deployment with a 'kernelci-pipeline-lava-callback' service with the default `pipeline.yaml`.
Steps to reproduce:
```
cd localinstall
python kci-deploy.py
cd kernelci/kernelci-pipeline
docker-compose -f docker-compose-lava.yaml up
```
Issue:
```
Traceback (most recent call last):
File "/home/kernelci/pipeline/lava_callback.py", line 34, in <module>
CONFIGS = kernelci.config.load(
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kernelci/config/__init__.py", line 191, in load
data = load_yaml(config_paths)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kernelci/config/__init__.py", line 149, in load_yaml
data = load_single_yaml(path)
^^^^^^^^^^^^^^^^^^^^^^
File …
```

Fix: remove non-existent reference in 'pipeline.yaml' for local deployment, build missing pipeline images

---

staging.kernelci.org

We are hitting github limits, lets poll less often workflow results.

Decrease API polling frequency

---

localinstall/2-install_api.sh

This PR fixes the generation of the `kernelci.toml` for `kernelci-core` for local deployment:
```
Traceback (most recent call last):
File "/var/home/tollsimy/lfx-mentorship/kernelCI/kernelci-deploy/localinstall/kernelci/kernelci-core/./kci", line 35, in <module>
main()
File "/var/home/tollsimy/lfx-mentorship/kernelCI/kernelci-deploy/localinstall/kernelci/kernelci-core/./kci", line 31, in main
kci()  # pylint: disable=no-value-for-parameter
^^^^^
File "/var/home/tollsimy/lfx-mentorship/kernelCI/kernelci-deploy/localinstall/env/lib64/python3.12/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/home/tollsimy/lfx-mentorship/kernelCI/kernelci-deploy/localinstall/env/lib64/python3.12/site-packages/click/core.py", line …
```

Fix kernelci.toml generation for local deployment

---

kubernetes/caching/azurefile-pvc.yaml
kubernetes/caching/croncache.yaml
kubernetes/caching/deploy-cacher.sh
kubernetes/caching/filestore-pvc.yaml

Related-to: https://github.com/kernelci/kernelci-core/issues/2883
We introduce PVC RWX volume and download once per day firmware file, to keep it fresh. This should reduce egress traffic on Azure.

(k8s) Introduce k8s caching volume
